### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by Nicogene** [robotology/rfsmTools#17]
TODO list:
- [x] Fix `qt` dependencies in Ubuntu 18.04
- [ ] Add installation instruction and `find_dependecy` usage (introduced in #15 )

**Comment by Nicogene** [comment]
Moreover, the link https://people.mech.kuleuven.be/~bruyninc/rFSM/doc/README.html, about the installation of rfsm it doesn't exist anymore :crying_cat_face:

**Comment by Nicogene** [comment]
The rfsm-guy moved to github : https://github.com/kmarkus/rFSM

**Comment by traversaro** [comment]
> 
> 
> The rfsm-guy moved to github : https://github.com/kmarkus/rFSM

Yes, even if it is not really maintained: https://github.com/kmarkus/rFSM/pull/6 .

**Comment by Nicogene** [comment]
> Yes, even if it is not really maintained: kmarkus/rFSM#6

:crying_cat_face:
