### ISSUE TITLE
scroll bar on output

### ISSUE THREAD

**Issue by tanismar** [robotology/rfsmTools#8]
Hi. 
When executing a stateMachine, sometimes the output message (specially if there is an error), exceeds the width of the output window. Right now the only way to see the full message is to make the whole rfsmTools window larger, which is quite cumbersome. Could a horizontal scrollbar be added to the output window, so all the messages could be read, independently of their length?
Thanks!
Tanis

**Comment by Nicogene** [comment]
Fixed by a5cb71fabf049da4bf468f04cac35f9faf7a253e, @tanismar thanks for reporting!
