### ISSUE TITLE
status bar message not updated after stop

### ISSUE THREAD

**Issue by miccol** [robotology/rfsmTools#9]
Hi,

the status bar keeps showing Running.../Paused! after the FSM is stopped.

It should be an easy fix calling showStatusBarMessage here (probably at the end o the scope)
https://github.com/robotology/rfsmTools/blob/ff555e150a4fc49ea01ee8fc1e56655fe8dc2459/rfsmGui/src/MainWindow.cpp#L651-L663

and / or here

https://github.com/robotology/rfsmTools/blob/ff555e150a4fc49ea01ee8fc1e56655fe8dc2459/rfsmGui/src/MainWindow.cpp#L665-L670

but you know better.

Nice tool!

MC

**Comment by Nicogene** [comment]
The commit 918bf594e78a8638aeaea49270d7b83d560406c1 should fix this issue.
Thanks for reporting!
